title: "Nebru"
description: "Music Composer"
baseurl: "" # for user/organization site, keep this empty
url: "" # set your custom domain or leave empty for github.io domain
theme: minima # or leave blank for custom styling
