title: "Nebru"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Minimal Mistakes specific settings
minimal_mistakes_skin: "air" # Try other skins!
logo: "/assets/images/logo.png"
